import enum

# https://bedrock.dev/docs/stable/Entities#Biome%20Tags
class BiomeTags(enum.Enum):
    """
    _
    """
    ANIMAL = "animal"
    BEACH = "beach"
    BIRCH = "birch"
    COLD = "cold"
    DARK_OAK = "dark_oak"
    DEEP = "deep"
    DESERT = "desert"
    EGE = "edge"
    EXTREME_HILLS = "extreme_hills"
    FLOWER_FOREST = "flower_forest"
    FOREST = "forest"
    FROZEN = "frozen"
    HILLS = "hills"
    ICE = "ice"
    ICE_PLAINS = "ice_plains"
    JUNGLE = "jungle"
    LAKES = "lakes"
    LUKEWARN = "lukewarm"
    MEGA = "mega"
    MESA = "mesa"
    MONSTER = "monster"
    MOOSHROOM_ISLAND = "mooshroom_island"
    MOUNTAIN = "mountain"
    MUTATED = "mutated"
    NETHER = "nether"
    OCEAN = "ocean"
    PLAINS = "plains"
    PLATEAU = "plateau"
    RIVER = "river"
    ROOFED = "roofed"
    SAVANNA = "savanna"
    SHORE = "shore"
    STONE = "stone"
    SWAMP = "swamp"
    TAIGA = "taiga"
    THE_END = "the_end"
    WARM = "warm"
