import enum

# https://wiki.bedrock.dev/blocks/block-sounds.html
# Last updated for 1.19.80
class BlockSounds(enum.Enum):
    """
    Minecraft Bedrock Block Sounds
    """
    AMETHYST_BLOCK = "amethyst_block"
    AMETHYST_CLUSTER = "amethyst_cluster"
    ANCIENT_DEBRIS = "ancient_debris"
    ANVIL = "anvil"
    AZALEA = "azalea"
    AZALEA_LEAVES = "azalea_leaves"
    BAMBOO = "bamboo"
    BAMBOO_SAPLING = "bamboo_sapling"
    BASALT = "basalt"
    BIG_DRIPLEAF = "big_dripleaf"
    BONE_BLOCK = "bone_block"
    CALCITE = "calcite"
    CANDLE = "candle"
    CAVE_VINES = "cave_vines"
    CHAIN = "chain"
    CLOTH = "cloth"
    COMPARATOR = "comparator"
    COPPER = "copper"
    CORAL = "coral"
    DEEPSLATE = "deepslate"
    DEEPSLATE_BRICKS = "deepslate_bricks"
    DIRT_WITH_ROOTS = "dirt_with_roots"
    DRIPSTONE_BLOCK = "dripstone_block"
    FROG_SPAWN = "frog_spawn"
    FROG_LIGHT = "froglight"
    FUNGUS = "fungus"
    GLASS = "glass"
    GRASS = "grass"
    GRAVEL = "gravel"
    HANGING_ROOTS = "hanging_roots"
    HONEY_BLOCK = "honey_block"
    ITEM_FRAME = "itemframe"
    LADDER = "ladder"
    LANTERN = "lantern"
    LARGE_AMETHYST_BUD = "large_amethyst_bud"
    SMALL_AMETHYST_BUD = "small_amethyst_bud"
    LEVER = "lever"
    LODESTONE = "lodestone"
    MANGROVE_ROOTS = "mangrove_roots"
    MUDDY_MANGROVE_ROOTS = "muddy_mangrove_roots"
    MEDIUM_AMETHYST_BUD = "medium_amethyst_bud"
    METAL = "metal"
    MOSS_BLOCK = "moss_block"
    MOSS_CARPET = "moss_carpet"
    MUD = "mud"
    MUD_BRICKS = "mud_bricks"
    NETHER_BRICK = "nether_brick"
    NETHER_GOLD_ORE = "nether_gold_ore"
    NETHER_SPROUTS = "nether_sprouts"
    NETHER_WART = "nether_wart"
    NETHER_WOOD = "nether_wood"
    NETHERITE = "netherite"
    NETHERRACK = "netherrack"
    NYLIUM = "nylium"
    PACKED_MUD = "packed_mud"
    POINTED_DRIPSTONE = "pointed_dripstone"
    POWDER_SNOW = "powder_snow"
    ROOTS = "roots"
    SAND = "sand"
    SCAFFOLDING = "scaffolding"
    SCULK = "sculk"
    SCULK_CATALYST = "sculk_catalyst"
    SCULK_SENSOR = "sculk_sensor"
    SCULK_SHRIEKER = "sculk_shrieker"
    SCULK_VEIN = "sculk_vein"
    SHROOM_LIGHT = "shroomlight"
    SLIME = "slime"
    SNOW = "snow"
    SOUL_SAND = "soul_sand"
    SOUL_SOIL = "soul_soil"
    SPORE_BLOSSOM = "spore_blossom"
    STEM = "stem"
    STONE = "stone"
    SWEET_BERRY_BUSH = "sweet_berry_bush"
    TUFF = "tuff"
    VINES = "vines"
    WOOD = "wood"