import enum

# https://wiki.bedrock.dev/items/enchantments.html
class Enchantments(enum.Enum):
    """
    Minecraft Bedrock Enchantments
    """
    SILK_TOUCH = "silk_touch"
    FORTUNE = "fortune"
    EFFICIENCY = "efficiency"
    LUCK_OF_THE_SEA = "luck_of_the_sea"
    LURE = "lure"
    SHARPNESS = "sharpness"
    SMITE = "smite"
    BANE_OF_ARTHROPODS = "bane_of_arthropods"
    FIRE_ASPECT = "fire_aspect"
    KNOCKBACK = "knockback"
    LOOTING = "looting"
    POWER = "power"
    FLAME = "flame"
    PUNCH = "punch"
    INFINITY = "infinity"
    MULTI_SHOT = "multishot"
    PIERCING = "piercing"
    QUICK_CHARGE = "quick_charge"
    IMPALING = "impaling"
    RIPTIDE = "riptide"
    LOYALTY = "loyalty"
    CHANNELING = "channeling"
    PROTECTION = "protection"
    PROJECTILE_PROTECTION = "projectile_protection"
    FIRE_PROTECTION = "fire_protection"
    BLASH_PROTECTION = "blast_protection"
    FEATHER_FALLING = "feather_falling"
    THORNS = "thorns"
    FROST_WALKER = "frost_walker"
    RESPIRATION = "respiration"
    AQUA_AFFINITY = "aqua_affinity"
    CURSE_OF_BINDING = "curse_of_binding"
    DEPTH_STRIDER = "depth_strider"
    SOUL_SPEED = "soul_speed"
    UNBREAKING = "unbreaking"
    MENDING = "mending"
    CURSE_OF_VANISHING = "curse_of_vanishing"